server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:clinicdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "change-this-secret-in-production-please"
    expirationMinutes: 120

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
